### ISSUE TITLE
Question: How is this this repo related to fjudith/docker-draw.io? 

### ISSUE THREAD

**Issue by Himura2la** [jgraph/docker-drawio#11]
![image](https://user-images.githubusercontent.com/7802808/89014733-a3def900-d31e-11ea-8dc5-eed270a98279.png)

There are changes in both repositories. so I can't consider this one a newer version of `fjudith/docker-draw.io`. 

Which one should I use to get the latest version?

**Comment by davidjgraph** [comment]
It is forked from that repo, originally.

**Comment by Himura2la** [comment]
How this repo is now synced with the upstream?
