### ISSUE TITLE
Docker gitlab authorization failed

### ISSUE THREAD

**Issue by homuraLan** [jgraph/docker-drawio#110]
First of all, can only use https？
If so, I can try the following again, otherwise please allow me to feedback 
I should use the latest image.
![image](https://user-images.githubusercontent.com/96775034/227609352-17a84a48-b7b9-4392-9881-d5c2ea589a3d.png)
But I still get this error. I've tried dozens of times and seen various issues
![image](https://user-images.githubusercontent.com/96775034/227609813-ba9f90c5-f021-4176-8d60-f60b3d4702b7.png)
I see this error spanning many major versions, and I hope it can attract attention.
Or provide a relatively complete tutorial  Thank you very much.

**Comment by homuraLan** [comment]
I use fjudith/draw.io and gitlab/gitlab-ce. I set all the parameters for gitlab

**Comment by davidjgraph** [comment]
If you're using fjudith/draw.io please submit the report to that repo. We cannot provide support for other people's repo.
