### ISSUE TITLE
why no PlantUML 

### ISSUE THREAD

**Issue by yuhui321** [jgraph/docker-drawio#113]
Why is there no PlantUML feature in the latest version of drawio? I am using version 21.3.4 of jgraph/drawio docker iamge

![image](https://github.com/jgraph/docker-drawio/assets/100281324/ce74dd6b-9e60-4331-b638-44c549e31395)

**Comment by davidjgraph** [comment]
Which docker image are you using?

**Comment by davidjgraph** [comment]
See #114
