### ISSUE TITLE
Only have device storage and the url cannot correctly display

### ISSUE THREAD

**Issue by MorganReid** [jgraph/docker-drawio#119]
I start a drawio service on `10.112.0.141` using the following command:
`docker run -it --rm --name="draw" -p 8080:8080 -p 54152:8443 jgraph/drawio`
Then I configured nginx:
![企业微信截图_16909613617923](https://github.com/jgraph/docker-drawio/assets/52235796/000c9f4e-b123-409c-ba82-689df98f1787)
Now I get the following by visiting https://dev.draw.autox.clu.
![image](https://github.com/jgraph/docker-drawio/assets/52235796/a6d99820-d86f-465f-978e-fbec5af3753c)
This seems to be normal, but why is there only `Device` option for storage?
After I go in, create a diagram, and then select `File-Export as-URL`.**This url is `viewer.diagrams.net` at the beginning, indicating that this file is stored in `viewer.diagrams.net`?**
![image](https://github.com/jgraph/docker-drawio/assets/52235796/ddfa1bdc-fc1e-4ab9-b9a4-f0e0c70569cd)
The expected exported url domain name should be `dev.draw.autox.clu`.
I checked the information and said that` DRAWIO_LIGHTBOX_URL` needs to be set, so I used the following command to restart the service.
`docker run -it --rm --name="draw" -e DRAWIO_LIGHTBOX_URL=dev.draw.autox.clu -p 8080:8080 -p 54152:8443 jgraph/drawio`
Unfortunately, when I visit `https://dev.draw.autox.clu` again, I get the following:
![image](https://github.com/jgraph/docker-drawio/assets/52235796/6feabf37-e4f1-4689-a1ef-462cc4769b5c)

It's not normal.
1: How can the storage location not only be limited to `Device`?
2: How to ensure that the domain name of the URL is the domain name of my server?
https://github.com/jgraph/docker-drawio/issues/116 have related question, but I didn't see an answer and it's closed.

**Comment by m-mohamedin** [comment]
Can you please check the README at https://github.com/jgraph/docker-drawio/tree/dev/self-contained and let us know if it has the answers you want?

**Comment by MorganReid** [comment]
> Can you please check the README at https://github.com/jgraph/docker-drawio/tree/dev/self-contained and let us know if it has the answers you want?

Thanks for your reply, the problem has been resolved.
1: If  want to add other storage methods,  only need to add the corresponding environment variables, such as: DRAWIO_GITLAB_ID&DRAWIO_GITLAB_SECRET&DRAWIO_GITLAB_URL.
2: Get the solution in this issue (https://github.com/jgraph/drawio/issues/3175).
