### ISSUE TITLE
Close Device and Browser storage

### ISSUE THREAD

**Issue by MorganReid** [jgraph/docker-drawio#123]
I self-deployed a service based on` jgraph/drawio` and successfully integrated it with `gitlab`. 
When using it, I was asked to select a storage.
![image](https://github.com/jgraph/docker-drawio/assets/52235796/cf4d0d88-3308-4a5c-836e-08f4ab53b72b)

In addition, I found that if  select `Decide later` when selecting storage, then draw, and then select `File` -> `save`, there will be an additional `Browser` option.
![image](https://github.com/jgraph/docker-drawio/assets/52235796/6b264c7b-2b9e-475b-a5d0-d9a2e316d3ba)

Now it is required to only store it on `gitlab`. Is there any way to turn off the `Device` and `Browser` option?

**Comment by davidjgraph** [comment]
If you can set a URL parameter use `mode=gl`.
