### ISSUE TITLE
Question: How to use self-provided SSL certificate?

### ISSUE THREAD

**Issue by purerosefallen** [jgraph/docker-drawio#13]
Our company has a system deploying our company's SSL certificate with Ansible. I wish we could mount our own SSL certificate and start drawio with HTTPS mode. But I failed to find any instructions related to this.
Could you be so kind as to point out how to provide our own certificate? thanks.

**Comment by davidjgraph** [comment]
It would be the same process as adding SSL to any Tomcat, see https://www.mulesoft.com/tcat/tomcat-ssl for example.
