### ISSUE TITLE
How to set default Language?

### ISSUE THREAD

**Issue by e4glet** [jgraph/docker-drawio#136]
How to set default Language?

**Comment by m-mohamedin** [comment]
You can use url parameter `?lang=en`
or `mxLanguage='en'` in PreConfig.js file

**Comment by zzhkhyl** [comment]
?lang=enmxLanguage='en',Where should this parameter be written? Is there any example to look at?

**Comment by davidjgraph** [comment]
https://app.diagrams.net/?lang=zh

**Comment by Tiande** [comment]
> [app.diagrams.net?lang=zh](https://app.diagrams.net/?lang=zh)

www.example.com/?lang=zh
