### ISSUE TITLE
Issue with DRAWIO_LIGHTBOX_URL and local viewer

### ISSUE THREAD

**Issue by pmenga52** [jgraph/docker-drawio#137]
Hi,
I would like to use the internal readonly viewer of the docker server (lightbox?)
dealing with the docs ( https://github.com/jgraph/docker-drawio/tree/dev/self-contained ), I tested several settings according to the DRAWIO_* parameters

I just installed last version of docker-drawio (22.04) on a local machine ( local DN draw.fc) with the simpliest docker-composed.yml for a local machine

_docker-compose.yml_

> version: '3.5'
> services:
>   drawio:
>     image: jgraph/drawio
>     container_name: drawio
>     restart: unless-stopped
>     ports:
>       - 80:8080
>       - 443:8443
>     environment:
>       DRAWIO_SERVER_URL: http://draw.fc
>       DRAWIO_BASE_URL: http://draw.fc/
>      #DRAWIO_VIEWER_URL: http://draw.fc
>      #DRAWIO_LIGHTBOX_URL: http://draw.fc
>     healthcheck:
>       test: ["CMD-SHELL", "curl -f http://draw.fc || exit 1"]
>       interval: 1m30s
>       timeout: 10s
>       retries: 5
>       start_period: 10s
> 

- first test: DRAWIO_VIEWER_URL and DRAWIO_LIGHTBOX_URL commented 
_drawio  | window.DRAWIO_SERVER_URL = 'http://draw.fc';
drawio  | window.DRAWIO_BASE_URL = 'http://draw.fc';
drawio  | window.DRAWIO_VIEWER_URL = '';
drawio  | window.DRAWIO_LIGHTBOX_URL = '';_

on the menu:
File/Publish/Link + lightbox checked, -> the url link start with https://viewer.diagrams.net  (not what I want)
File/Publish/Link + lightbox unchecked, -> the url link starts with http://draw.fc but still on edit mode (not read-only)

- second test: DRAWIO_VIEWER_URL=http://draw.fc DRAWIO_LIGHTBOX_URL commented:
same results

- third test: DRAWIO_LIGHTBOX_URL=http://draw.fc
--> the client stops with the error message "Error loading file" - no file selected 

So at the end, I don't know if the DRAWIO_LIGHTBOX_URL is correctly set (and how it could retrieve the /js/viewer.min.js

**Comment by m-mohamedin** [comment]
DRAWIO_LIGHTBOX_URL in current version must be different from the BASE/SERVER URL (e.g, a different subdomain)

In the next version, we'll remove this limitation

**Comment by davidjgraph** [comment]
In 22.1.17
