### ISSUE TITLE
Missing shapes when loading .xml file - only empty rectangles displayed

### ISSUE THREAD

**Issue by linuxrrze** [jgraph/docker-drawio#14]
Hi there,

when using the docker container for editing draw.io .xml files certain shapes cannot be displayed (rectangles are shown instead in the diagram and also in the shapes selection box on the left hand side).

Loading the same .xml file in the official instance works fine.

During load of the .xml file (or when opening the (e.g. "Arrow") shapes tabs the browser developer console reports:

> error in getStencil: shapes/mxAWS4.js EvalError: Refused to evaluate a
> string as JavaScript because 'unsafe-eval' is not an allowed source of
> script in the following Content Security Policy directive: "script-src
> 'self' https://storage.googleapis.com https://apis.google.com
> https://docs.google.com https://code.jquery.com 'unsafe-inline'".
> 
>     at eval (<anonymous>)
>     at Object.mxStencilRegistry.getStencil (app.min.js:2820)
>     at mxCellRenderer.createShape (app.min.js:1165)
>     at mxCellRenderer.createShape (app.min.js:2818)
>     at mxCellRenderer.redrawShape (app.min.js:1206)
>     at mxCellRenderer.redraw (app.min.js:1205)
>     at mxGraphView.validateCellState (app.min.js:1266)
>     at mxGraphView.validateCellState (app.min.js:2807)
>     at mxGraphView.validateCellState (app.min.js:1266)
>     at mxGraphView.validateCellState (app.min.js:2807)
> app.min.js:2820 error in getStencil: shapes/mxArrows.js EvalError:
> Refused to evaluate a string as JavaScript because 'unsafe-eval' is
> not an allowed source of script in the following Content Security
> Policy directive: "script-src 'self' https://storage.googleapis.com
> https://apis.google.com https://docs.google.com
> https://code.jquery.com 'unsafe-inline'".
> 
>     at eval (<anonymous>)
>     at Object.mxStencilRegistry.getStencil (app.min.js:2820)
>     at mxCellRenderer.createShape (app.min.js:1165)
>     at mxCellRenderer.createShape (app.min.js:2818)
>     at mxCellRenderer.redrawShape (app.min.js:1206)
>     at mxCellRenderer.redraw (app.min.js:1205)
>     at mxGraphView.validateCellState (app.min.js:1266)
>     at mxGraphView.validateCellState (app.min.js:2807)
>     at mxGraphView.validateCellState (app.min.js:1266)
>     at mxGraphView.validateCellState (app.min.js:2807)

First I observed this behaviour from within my nextcloud instance.
However when using just plain docker (and apache proxy) and loading the file from local storage it gave exactly the same errors.

**Comment by linuxrrze** [comment]
Looks like this (in the shapes tab):

![Unbenannt](https://user-images.githubusercontent.com/18438286/96451155-7320a880-1217-11eb-86eb-dfff526218a0.png)

**Comment by equatebrand** [comment]
I was able to 'fix' it by adding the following environmental flag to the docker run command:

`-e DRAWIO_CSP_HEADER="default-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; connect-src \'self\' https://*.draw.io https://fonts.googleapis.com https://fonts.gstatic.com; img-src * data:; media-src *; font-src *; style-src-elem \'self\' \'unsafe-inline\' \'unsafe-eval\' https://fonts.googleapis.com"`

Basically, I added **unsafe-eval** to the Content-Security-Policy bit from this code on https://localhost:8443

`(function()
{
	var name = 'diagrams.net';
	mxmeta('apple-mobile-web-app-title', name);
	mxmeta('application-name', name);
	if (mxIsElectron)
	{
		mxmeta(null, 'default-src \'self\' \'unsafe-inline\'; connect-src \'self\' https://*.draw.io https://fonts.googleapis.com https://fonts.gstatic.com; img-src * data:; media-src *; font-src *; style-src-elem \'self\' \'unsafe-inline\' https://fonts.googleapis.com', 'Content-Security-Policy');
	}
})();`

I'm sure there are a billion better ways to do this, but if you don't care about security...

**Comment by equatebrand** [comment]
You MIGHT have to specify DRAWIO_BASE_URL, too. I'm not sure. Documentation is here: https://github.com/jgraph/docker-drawio/blob/master/self-contained/README.md

**Comment by Floppsi1** [comment]
Hello, 

The solution of equatebrand is working and everything is displayed again correctly, but what would be the correct solution?
Could any of the developers give a feedback?

Thanks a lot.

**Comment by davidjgraph** [comment]
Dynamic loading was removed from the build recently, so you shouldn't encounter this again.
