### ISSUE TITLE
Export to PDF is creating a blank page 

### ISSUE THREAD

**Issue by jjasoncool** [jgraph/docker-drawio#147]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
draw.io docker container selfhost can't export PDF files, png and svg is normal.

**To Reproduce**
Just simple export PDF
![圖片](https://github.com/jgraph/drawio/assets/24731867/5cb7b6fd-deaa-41fd-832e-e3e89c700fb8)

Will pop page 404, and url is `https://mydomain/service/0`
![圖片](https://github.com/jgraph/drawio/assets/24731867/3f51c45f-1b05-4dc0-b738-7c529bab945f)

**Expected behavior**
- download exported PDF file.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 22.1.4

**Desktop (please complete the following information):**
 - OS: windows/Linux
 - Browser firefox
 - Browser Version 120.0

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes

**Additional context**
My Drawio is selfhost using docker-compose
```docker-compose
  drawio:
    image: jgraph/drawio:${DWIO_VERSION}
    container_name: drawio
    restart: always
    environment:
      - DRAWIO_SELF_CONTAINED=1
      - DRAWIO_BASE_URL=https://${HOST_DOMAIN}
      - DRAWIO_SERVER_URL=https://${HOST_DOMAIN}/drawio/
      # why doesn't use EXPORT_URL to export PDF?
      - EXPORT_URL=http://image-export:8000/
    depends_on:
      - nginx

  image-export:
    image: jgraph/export-server:latest
    container_name: drawio-export
    expose:
      - "8000"
    environment:
      - DRAWIO_BASE_URL=https://${HOST_DOMAIN}
    volumes:
      - ./drawio/fonts:/usr/share/fonts/drawio
    restart: always
```
REF: https://github.com/jgraph/docker-drawio/blob/dev/nextcloud/docker-compose.yml

The EXPORT_URL  use docker local domain like upon example, but drawio don't send request to export-server

**Comment by jjasoncool** [comment]
https://github.com/jgraph/docker-drawio/issues/128

**Comment by m-mohamedin** [comment]
The two containers need to be in the same docker network. Did you try the original docker compose file?
