### ISSUE TITLE
Share Mouse Cursor

### ISSUE THREAD

**Issue by Janokisu** [jgraph/docker-drawio#160]
Hi,
is it possible to use Share Mouse Cursor with this image?
When I use https://embed.diagrams.net in Nextcloud it works, but when I use this image (behind a nginx reverse-proxy) it doesn't work.

Nextcloud: 28.0.6
Draw.io-App: 3.0.2
drawio-image: 24.4.8

**Comment by davidjgraph** [comment]
No, we don't have proper collaborative editing support here yet. The collab comes from code written specifically for Cloudflare workers, so isn't remotely portable.

It's something we're aware of, the intention is to have as much of the project available as possible, but as long as it doesn't cause us excess work to do so.
