### ISSUE TITLE
same save options like at https://app.diagrams.net possible?

### ISSUE THREAD

**Issue by gsg-git** [jgraph/docker-drawio#169]
Hello!

I just installed the container and have just the save in browser option aviable.
Do i have to anebale some kind of plugins, because at least saving in Nextcloud would be useful to us.

My Container:
![grafik](https://github.com/user-attachments/assets/55b9a558-6b7b-4230-bf87-5bfdbd2b2d9c)
Official one:
![grafik](https://github.com/user-attachments/assets/65bb4072-09a9-4a07-b622-b8552f2d7266)

Thank you in advance!!!

**Comment by davidjgraph** [comment]
you need the nextcloud app for nextcloud integration.

**Comment by gsg-git** [comment]
@davidjgraph 
I dont understand what you mean: is there an Plugin which has to be installed in my diagrams container or do i have to configure in Nextclout to enble to save in Nextcloud in my diagrams container?

**Comment by gsg-git** [comment]
I found those where i would store the credentials for all, but see no for NC:
![grafik](https://github.com/user-attachments/assets/062aabb8-a27e-4037-a271-6b1a120dad2f)



I obverlooked NC is not directly in storage option integrated and i would have to install the drawio app and configure my Container there.
But im still courious about the other Storage options like gitlab.

**Comment by gsg-git** [comment]
for me its solved, because there is an draw io software wich i didnt knew until now
