### ISSUE TITLE
CVEs in Image - Automated builds

### ISSUE THREAD

**Issue by lordfolken** [jgraph/docker-drawio#21]
Hello, 

https://github.com/aquasecurity/trivy scanner reports currently 356 Vulnerabilities of which 18 are critical, and 65 have patches.
Automated Builds would probably go a long way in fixing these.

Regards,
 - Folken

**Comment by davidjgraph** [comment]
The build is automated. It also needs to be repeatable and running apt upgrade or similar breaks that. You're welcome to submit a PR for how to improve the current process.

**Comment by lordfolken** [comment]
You need to rebuild the whole image. Apt-get would as you state create a mess and unnecessarily enlarge the container. 
see pr #22 
Unfortunately as long as container images are based on docker, this means a full pull.
