### ISSUE TITLE
Is it possible to have personal 'viewer.diagrams.net' ?

### ISSUE THREAD

**Issue by rootnoir** [jgraph/docker-drawio#23]
Hi! We use docker-drawio in local network, and it's work greate! 
But we need viewer.diagrams.net functional.. and seems there is no docker image for it..

Is it possible to have personal 'viewer.diagrams.net' ?

**Comment by davidjgraph** [comment]
viewer.diagrams.net maps to exactly the same code as app.diagrams.net.

**Comment by rootnoir** [comment]
> viewer.diagrams.net maps to exactly the same code as app.diagrams.net.

shure, but how to get it in container? i can't find any settings, to make viewer from app ) 
it should always use lightbox=1 i guess..

**Comment by davidjgraph** [comment]
Probably, yes, but then this is a duplicate of your other issue.

**Comment by rootnoir** [comment]
> Probably, yes, but then this is a duplicate of your other issue.

yes.. when we get a solution, i'll close both )

**Comment by rootnoir** [comment]
Solution: https://github.com/jgraph/drawio/issues/1855#issuecomment-790499581
