### ISSUE TITLE
Question:  How can i setup google drive and cloud save after install from docker? Theres a manual about it?

### ISSUE THREAD

**Issue by doug3d** [jgraph/docker-drawio#26]
Hey, 
i had installed drawio from docker on my PLESK server and it's working. Almost 90%.   

I want to know how can i config the Oauth2 to run from my server.
If theres a manual where i can learn how to do it i will appreciate

thanks!

**Comment by danijel1310** [comment]
https://github.com/jgraph/docker-drawio/tree/dev/self-contained
