### ISSUE TITLE
Gitlab OAuth2 unable authorized

### ISSUE THREAD

**Issue by superego** [jgraph/docker-drawio#27]
I configured my own drawio with docker container and connect it to my gitlab which domain name is git.tuogo.com.cn.
When I click authorize gitlab in drawio, it can redirect to my gitlab, and return from gitlab. But I can't display correct content, finally I have got http error code 400 as follow link:

http://draw.tuogo.com.cn/gitlab?code=4ae0a35ec1742b15be1523b8dbff0383ae1e22486187633a69491825d7413012&state=cId%3D074605aaff49198814d7f57ee3a9c7476b186e51a3e58c809e47fdcfd3e421e2%26domain%3Ddraw.tuogo.com.cn%26token%3Dsogidtmn8krqraq8dktgs27ltpcvulrof8d6v0icek258vcle2j

<img width="1136" alt="Screen Shot 2021-05-15 at 4 04 48 PM" src="https://user-images.githubusercontent.com/2410152/118353172-b669ac80-b597-11eb-8439-ee5b734ca4be.png">

Gitlab version: 13.11

How should I fix this problem? Thanks.

**Comment by drriguz** [comment]
I got same issue, can anyone share how this get solved?
