### ISSUE TITLE
Question: CLI generate svg from csv

### ISSUE THREAD

**Issue by userstan** [jgraph/docker-drawio#28]
Hello!
I want to generate svg image from csv report (for example hardware inventory or webapps dependencies).
Now I use selenium to simulate import csv -> export svg.

May be exist cli tool for import csv -> export svg?
Thanks!

**Comment by m-mohamedin** [comment]
You can have a look at the desktop app
https://github.com/jgraph/drawio-desktop/

There are some docker images using it for a dockerized export (but not maintained by JGraph)
