### ISSUE TITLE
Question: how to set Access-Control-Allow-Origin header 

### ISSUE THREAD

**Issue by zhenevskiys** [jgraph/docker-drawio#32]
Hello!
I upload csv to self-hosted drawio (via [drawio-tools/csv](https://github.com/jgraph/drawio-tools/blob/master/tools/csv.html)).
I set CSP header into PreConfig.js (warning! this is only lab env):

```javascript
s.setAttribute('content', 'default-src \'self\'; script-src \'self\' \'unsafe-inline\'; connect-src \'self\' http://tools.lab; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\'');
```

And now I have CORS policy error : No 'Access-Control-Allow-Origin' header is present on the requested resource.
But with disable CORS, I have good result.

Thanks all!

**Comment by davidjgraph** [comment]
Set DRAWIO_CSP_HEADER as an environment variable. The docker composes have the full list of env variable, e.g. https://github.com/jgraph/docker-drawio/blob/dev/self-contained/docker-compose.yml
