### ISSUE TITLE
Real-time collab: mxPusher lambda function instructions

### ISSUE THREAD

**Issue by Nino171** [jgraph/docker-drawio#33]
Hey community!

firstly, thank you for your work. I really enjoy using drawio!

While working on my bachelor thesis, i tried to enable the real-time collaboration for my self-deployed drawio. I followed the instructions of the readme, but could not find any instructions nor folder regarding the mentioned "etc/mxPusher", which should explain the steps needed to "setup a lambda function for temporary keys as well as setting a role for that lambda function"

I would really appreciate it, if you could give me more informations regarding this.

I got the "Thing" working in my AWS and have also filled in alls cert/keys.

"DRAWIO_MXPUSHER_ENDPOINT" is the only thing that I am missing right now.
After testing drawio nothing seems to synchronise (using oneDrive), and that is why i think that this endpoint variable is crucial.

Thank you in advance!

**Comment by holgerbrandl** [comment]
Where did you find the instructions to enable the collaborative using a local docker deployment? Could you find a workaround for the problem described above?

**Comment by davidjgraph** [comment]
Let's deal with the original issue in this thread and please open a new one for your new question.

**Comment by davidjgraph** [comment]
Actually, I don't think we have that variable any longer :D. Sorry, it took so long to look.
