### ISSUE TITLE
typo in hub.docker.com

### ISSUE THREAD

**Issue by kireita** [jgraph/docker-drawio#42]
There is a typo in the hub.docker.com page it says:
fjudith/draw.io with the (dot) in between instead of fjudith/drawio  without the (dot)

this was a previous issue probably corrected on github but not on hub.docker.com.

![image](https://user-images.githubusercontent.com/25864917/132596387-33349ca9-7196-4cb0-9fa8-3f06e33b2e8f.png)

**Comment by davidjgraph** [comment]
That's not our image, our image is https://hub.docker.com/r/jgraph/drawio

**Comment by kireita** [comment]
Oke sorry, but it it still has the same error apparently
![IMG_20210909_145024.jpg](https://user-images.githubusercontent.com/25864917/132688892-a43e74b6-a3ca-4f84-be6f-7c64bbaf6720.jpg)

**Comment by davidjgraph** [comment]
Fixed, thanks.
