### ISSUE TITLE
[Security] Update tomcat

### ISSUE THREAD

**Issue by TheSinding** [jgraph/docker-drawio#49]
I've just noticed the alpine dockerfile uses a Tomcat image from **3 years** ago.
A Snyk analysis says there is **87** security flaws and **17** is high risk
[source](https://snyk.io/test/docker/tomcat:9-jre8-alpine)

Is it easily updatable ?

**Comment by VerscheldeAlynne** [comment]
@TheSinding https://overreacted.io/npm-audit-broken-by-design/

**Comment by TheSinding** [comment]
Yeah and as I might agree with some of that - Having an image 3 years old and with the introduction of the new Log4J CVE, it might be worth considering to update the image, dont you think ?

**Comment by TheSinding** [comment]
But it is in the Tomcat image or am I wrong ?
