### ISSUE TITLE
It should allow to edit graphs in collaboration when using a local docker installation

### ISSUE THREAD

**Issue by holgerbrandl** [jgraph/docker-drawio#56]
Currently, only "save on device" and "save in browser" are offered, and neither seems to provide collaboration capabilities.

If collaboration using a docker installation is supported already, it would be great if the documentation could be extended to illustrate how to do so.

**Comment by davidjgraph** [comment]
I don't have time to write everthing, please make a specific request.

**Comment by holgerbrandl** [comment]
I'd find _It should allow to edit graphs in collaboration when using a local docker installation_ specific. Not sure how to improve it.

**Comment by davidjgraph** [comment]
You'd need to configure one of the two cloud storage options that does collab, Google Drive or OneDrive.

**Comment by holgerbrandl** [comment]
Thanks for the help & hint. Thanks to it, I've discovered https://github.com/jgraph/docker-drawio/blob/dev/self-contained/README.md#configuration accordingly and now have a good lead to follow up on.
