### ISSUE TITLE
PDF export with self hosted export-server not working without connection to http://draw.io

### ISSUE THREAD

**Issue by Floppsi1** [jgraph/docker-drawio#6]
Dear all,

I am using the docker compose file from the self-contained folder
https://github.com/jgraph/docker-drawio/tree/master/self-contained

Everything is working fine, but when I want to export the PDF, http://draw.io is connected, but as Docker has no internet connection the PDF export fails. With internet connection the PDF is downloaded from draw.io.
PlantUML Server is working fine and I do get the results.

9f368b6c4a65        jgraph/drawio              "/docker-entrypoint.…"   8 minutes ago       Up 2 minutes        0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp   self-contained_drawio_1
6d1b18ebfffe        plantuml/plantuml-server   "/docker-entrypoint.…"   8 minutes ago       Up 2 minutes        8080/tcp                                         self-contained_plantuml-server_1
3fc1ad96b77c        jgraph/export-server       "docker-entrypoint.s…"   8 minutes ago       Up 2 minutes        8000/tcp                                         self-contained_image-export_1

Here the error log of the export-server:
image-export_1     | warn: Handled exception: net::ERR_CONNECTION_REFUSED at https://www.draw.io/export3.html req=ip=::ffff:192.168.144.4 format=pdf w=0 h=0 bg=#ffffff  {"stack":"Error: net::ERR_CONNECTION_REFUSED at https://www.draw.io/export3.html\n    at navigate (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/FrameManager.js:120:37)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/Page.js:674:49)\n    at Page.<anonymous> (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/helper.js:112:23)\n    at handleRequest (/usr/local/drawio/draw-image-export2/export.js:415:16)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
image-export_1     | ::ffff:192.168.144.4 - - [28/Jan/2020:03:50:04 +0000] "POST / HTTP/1.1" 500 - "http://192.168.1.105:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"

Do you have any idea, what I do wrong?
I thought that the export-server is considered to work offline.

Thank you.

Best regards,
Floppsi

**Comment by davidjgraph** [comment]
What have you set EXPORT_URL to in the PreConfig.js file?

**Comment by Floppsi1** [comment]
I did use the original configuration from here from github.

// Overrides of global vars need to be pre-loaded
window.EXPORT_URL = '/service/0'; //This points to ExportProxyServlet which uses the local export server at port 8000. 
							   //This proxy configuration allows https requests to the export server via Tomcat.
window.PLANT_URL = '/service/1';

**Comment by ashrafteleb** [comment]
Fixed
Just download the docker compose file again

**Comment by Floppsi1** [comment]
thanks, works now.

**Comment by darkstar2002** [comment]
Downloaded a fresh docker compose file and it is not using the export image like it is supposed to.
