### ISSUE TITLE
load custom library

### ISSUE THREAD

**Issue by ricardocapeli** [jgraph/docker-drawio#60]
I would know to if like Is there any possibility to put a customized library with my own shapes to the left shape bar for all users?
Every time I create a new diagram I have to add my customized library to the shape bar and each of the users they do the same thing.

Is there any way when I start the docker container it loads my library automatically and it makes my library visible to all users?

![image](https://user-images.githubusercontent.com/36749712/152179040-1bfc90b8-d51f-46f5-97cd-f881f2126abd.png)

Command currently used to make drawio available:

```
docker run -d --name drawio -p 8081:8080 fjudith/draw.io:8.2.3
```

**Comment by AneeshBhatnagar** [comment]
I've been looking to do something similar too, but haven't found any options yet, unfortunately. Is there something that worked for you?

**Comment by davidjgraph** [comment]
Does setting custom libs in the config not work?

**Comment by AneeshBhatnagar** [comment]
Is there an example of how to set it up on the config? I didn't see anything sadly

**Comment by vindelbo** [comment]
On the windows app i can add lots of custom libs permanently (not just browser cache) but has the limitations of a windows app. 
I wish to self host a draw.io in docker with ALL the libs i can find.
A solution where we could add url's or folder(s) to config would help.
I expect that the init "boot up" of draw io is slow but that's on my docker host. All users will have all the libs and doesn't have to add them manually. 

Is it possible and if so, are there any guides ?
