### ISSUE TITLE
Exported PNG have X placeholder images

### ISSUE THREAD

**Issue by eddiezab** [jgraph/docker-drawio#63]
Using the latest  (16.6.4 at time of writing) drawio from docker-hub my exported images appear similar to https://github.com/jgraph/drawio/issues/1160

I am using the default diagram generated from the CSV import for testing. I've tried exporting in Linux and Windows using Brave, Chrome, Firefox and Edge, all with the same result as shown below.

![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/2179170/155992706-c8511c11-bc3f-4d3e-8488-da9470e95bd1.png)

**Comment by gemad** [comment]
I have the same problem, using Draw.io extension v1.6.6.6  on visual studio code v1.82.1 on Ubuntu 21

**Comment by aleprovencio** [comment]
Here this issue happens on the flatpak version but not on the appimage.

**Comment by davidjgraph** [comment]
@eddiezab do you still see the issue?

**Comment by eddiezab** [comment]
TBH, I gave up trying to get it to work with the dockerized version, so instead at the time I needed this, I ended up automating it with the hosted version using pyppeteer. So I no longer know if it's an issue or not.

**Comment by aleprovencio** [comment]
Is there already a fix/workaround for this?

**Comment by davidjgraph** [comment]
Your issue is nothing to do with the original poster's. The issue is closed as the OP isn't interested any longer.
