### ISSUE TITLE
Onedrive support not working anymore

### ISSUE THREAD

**Issue by CharlPels** [jgraph/docker-drawio#67]
https issue solved however

Onedrive will give errors like [object Object] error.

older versions with same config and same environment settings is working fine.

container log error
11-Mar-2022 17:52:13.953 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1581] milliseconds
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by ashrafteleb** [comment]
Try the latest image and let us know

**Comment by CharlPels** [comment]
Fresh container with no custom server.xml or something
Environment vars for



CATALINA_HOME | /usr/local/tomcat
-- | --
DRAWIO_BASE_URL | https://drawio.mydomain.nl
DRAWIO_MSGRAPH_CLIENT_ID | removed here
DRAWIO_MSGRAPH_CLIENT_SECRET | removed here
GPG_KEYS | A9C5DF4D22E99998D9875A5110C01C5A2F6059E7
JAVA_HOME | /opt/java/openjdk
JAVA_VERSION | jdk-11.0.13+8
LANG | en_US.UTF-8
LANGUAGE | en_US:en
LC_ALL | en_US.UTF-8
LD_LIBRARY_PATH | /usr/local/tomcat/native-jni-lib
LETS_ENCRYPT_ENABLED | false
PATH | /usr/local/tomcat/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PUBLIC_DNS | drawio.mydomain.nl
TOMCAT_MAJOR | 10
TOMCAT_NATIVE_LIBDIR | /usr/local/tomcat/native-jni-lib
TOMCAT_SHA512 | e084fc0cc243c0a9ac7de85ffd4b96d00b40b5493ed7ef276d91373fe8036bc953406cd3c48db6b5ae116f2af162fd1bfb13ecdddf5d64523fdd69a9463de8a3
TOMCAT_VERSION | 10.0.12




/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Init PreConfig.js
(function() {
  try {
	    var s = document.createElement('meta');
	    s.setAttribute('content', 'default-src \'self\'; script-src \'self\' https://storage.googleapis.com https://apis.google.com https://docs.google.com https://code.jquery.com \'unsafe-inline\'; connect-src \'self\' https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com; img-src * data:; media-src * data:; font-src * about:; style-src \'self\' \'unsafe-inline\' https://fonts.googleapis.com;');
	    s.setAttribute('http-equiv', 'Content-Security-Policy');
 	    var t = document.getElementsByTagName('meta')[0];
      t.parentNode.insertBefore(s, t);
  } catch (e) {} // ignore
})();
window.DRAWIO_BASE_URL = 'https://drawio.<mydomain here>.nl';
window.DRAWIO_VIEWER_URL = '';
window.DRAW_MATH_URL = 'math';
window.DRAWIO_CONFIG = null;
urlParams['sync'] = 'manual'; //Disable Real-Time
urlParams['db'] = '0'; //dropbox
urlParams['gh'] = '0'; //github
urlParams['tr'] = '0'; //trello
urlParams['gapi'] = '0'; //Google Drive
window.DRAWIO_MSGRAPH_CLIENT_ID = '<removed >'; 
urlParams['gl'] = '0'; //Gitlab
Init PostConfig.js
window.VSD_CONVERT_URL = null;
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
App.prototype.isDriveDomain = function() { return true; }
Generating Self-Signed certificate
/docker-entrypoint.sh: line 141: keytool: command not found
/docker-entrypoint.sh: line 143: keytool: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /opt/java/openjdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
/usr/local/tomcat/bin/catalina.sh: line 421: /opt/java/openjdk/bin/java: No such file or directory

**Comment by ashrafteleb** [comment]
This is still Tomcat 10, please pull the latest version again (v17.1.3) and try again

**Comment by CharlPels** [comment]
Sorry when i pull latest version and deploy a fresh one from it, that is the information i got. It is latest ant won’t start or better it stops on that error.

**Comment by ashrafteleb** [comment]
Maybe this is due to we updated the image in-place using the same version number. Let's wait for v17.1.4 within the next week or delete the image completely and pull it again

It should show TOMCAT_VERSION=9.0.60

**Comment by dveretennikov1** [comment]
Hi, I also have the same error on a fresh install
```drawio    | 25-Apr-2022 11:29:13.461 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.62
drawio    | 25-Apr-2022 11:29:13.462 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 31 2022 14:34:15 UTC
drawio    | 25-Apr-2022 11:29:13.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.62.0
drawio    | 25-Apr-2022 11:29:13.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
drawio    | 25-Apr-2022 11:29:13.465 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.0-11-amd64
drawio    | 25-Apr-2022 11:29:13.466 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
drawio    | 25-Apr-2022 11:29:13.466 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
drawio    | 25-Apr-2022 11:29:13.467 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.14.1+1
drawio    | 25-Apr-2022 11:29:13.468 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
drawio    | 25-Apr-2022 11:29:13.468 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
drawio    | 25-Apr-2022 11:29:13.469 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
```

```
drawio    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
drawio    | SLF4J: Defaulting to no-operation (NOP) logger implementation
drawio    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by ashrafteleb** [comment]
Any errors logged when you try to open OneDrive?

**Comment by dveretennikov1** [comment]
Sorry, didn't receive notification about your answer. 
only errors I described previously
Today updated docker image to the latest, now I've got an error
![image](https://user-images.githubusercontent.com/102303381/169018054-f01d4d45-1e22-4fd9-a16b-394a97954a94.png)

**Comment by m-mohamedin** [comment]
@dveretennikov1 Please send us the server log and browser console log + network response of that request
Thanks

**Comment by dveretennikov1** [comment]
### console log

`VM72:1 Refused to connect to 'https://www.draw.io/notifications' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.dropboxapi.com https://api.trello.com https://api.github.com https://raw.githubusercontent.com https://*.googleapis.com https://*.googleusercontent.com https://graph.microsoft.com https://*.1drv.com https://*.sharepoint.com https://gitlab.com https://*.google.com https://fonts.gstatic.com https://fonts.googleapis.com".

(anonymous) @ VM72:1
mxXmlRequest.send @ app.min.js:610
get @ app.min.js:520
App.fetchAndShowNotification @ app.min.js:12740
App.updateButtonContainer @ app.min.js:12738
EditorUi.updateUi @ app.min.js:12073
App @ app.min.js:12557
q @ app.min.js:12571
(anonymous) @ app.min.js:12564
s.onload.s.onreadystatechange @ (index):172`

### docker log

```drawio    | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.304 WARNING [main] org.apache.catalina.core.StandardContext.setPath A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
drawio    | 18-May-2022 10:33:52.362 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.62
drawio    | 18-May-2022 10:33:52.364 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 31 2022 14:34:15 UTC
drawio    | 18-May-2022 10:33:52.365 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.62.0
drawio    | 18-May-2022 10:33:52.365 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
drawio    | 18-May-2022 10:33:52.366 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.0-11-amd64
drawio    | 18-May-2022 10:33:52.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
drawio    | 18-May-2022 10:33:52.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
drawio    | 18-May-2022 10:33:52.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.15+10
drawio    | 18-May-2022 10:33:52.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
drawio    | 18-May-2022 10:33:52.369 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
drawio    | 18-May-2022 10:33:52.370 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
drawio    | 18-May-2022 10:33:52.371 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.372 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.373 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.373 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.374 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
drawio    | 18-May-2022 10:33:52.374 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
drawio    | 18-May-2022 10:33:52.375 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
drawio    | 18-May-2022 10:33:52.376 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
drawio    | 18-May-2022 10:33:52.376 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
drawio    | 18-May-2022 10:33:52.377 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
drawio    | 18-May-2022 10:33:52.377 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
drawio    | 18-May-2022 10:33:52.378 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
drawio    | 18-May-2022 10:33:52.378 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
drawio    | 18-May-2022 10:33:52.379 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
drawio    | 18-May-2022 10:33:52.386 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.32] using APR version [1.7.0].
drawio    | 18-May-2022 10:33:52.388 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [true].
drawio    | 18-May-2022 10:33:52.388 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
drawio    | 18-May-2022 10:33:52.395 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1n  15 Mar 2022]
drawio    | 18-May-2022 10:33:53.073 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
drawio    | 18-May-2022 10:33:53.140 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio-8443"]
drawio    | 18-May-2022 10:33:53.883 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1939] milliseconds
drawio    | 18-May-2022 10:33:53.977 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
drawio    | 18-May-2022 10:33:53.977 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.62]
drawio    | 18-May-2022 10:33:54.776 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
drawio    | 18-May-2022 10:33:54.857 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/draw]
drawio    | 18-May-2022 10:33:55.155 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
drawio    | 18-May-2022 10:33:55.160 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/draw] has finished in [303] ms
drawio    | 18-May-2022 10:33:55.163 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
drawio    | 18-May-2022 10:33:55.205 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio-8443"]
drawio    | 18-May-2022 10:33:55.210 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1326] milliseconds
drawio    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
drawio    | SLF4J: Defaulting to no-operation (NOP) logger implementation
drawio    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.```

**Comment by m-mohamedin** [comment]
@dveretennikov1 So, the authorize window of Microsoft is open, and after selecting your account, you get the Access denied error? No Errors in Microsoft authentication window?

If this is the case, can you check the browser console -> Network tab and search for "microsoft", there should be two requests. Do both return status 200

**Comment by m-mohamedin** [comment]
Also, clear browser cache and then navigate to /clear.html

**Comment by dveretennikov1** [comment]
Yes, no errors on auth MS. I type my credentials and got an error.
clear cache and cookies - done
![image](https://user-images.githubusercontent.com/102303381/169038002-79940cb8-181c-4a62-9825-99d0109edce8.png)

**Comment by m-mohamedin** [comment]
@dveretennikov1 Can you please change the code in OneDriveClient.js and remove line 370: authWindow.close();
Then open the browser console of MS auth window and check the response for any errors in the network/console log

**Comment by dveretennikov1** [comment]
I logged into docker container, installed vim, edited OneDriveClient.js
```
                                                        else if (authWindow != null)
                                                        {
                                //                              authWindow.close();
                                                        }

```
save the file (but didn't restart docker container), clean cache and cookie and got the same error

**Comment by m-mohamedin** [comment]
@dveretennikov1 Yes, you'll get the same error but you'll get a chance to check the response returned in the auth window. The error is there. Please open the browser console of that auth window before starting the auth process and when done, check the console and network response
