### ISSUE TITLE
Question: Is there an smaller (disk space) version of the export server?

### ISSUE THREAD

**Issue by loganmarchione** [jgraph/docker-drawio#7]
The [jgraph/drawio docker image](https://hub.docker.com/r/jgraph/drawio) has two versions, a normal and alpine version.

- Normal ([jgraph/drawio:latest](https://hub.docker.com/layers/jgraph/drawio/latest/images/sha256-88c06c36d0033895a7bb947f1883668d7daf5de22431aea01bcdb27f988d125c)) ≈ 243MB compressed (667MB uncompressed)
- Alpine ([jgraph/drawio:alpine](https://hub.docker.com/layers/jgraph/drawio/alpine/images/sha256-1773fb17e4041f0c113dc9a9877a1f45be56fadbd3218f12a10b11f4d36399b0)) ≈ 143MB compressed (281MB uncompressed)

The Docker image for the [export server](https://hub.docker.com/layers/jgraph/export-server/latest/images/sha256-1d947bb1e3447812342f234df9f2843b51a50853c06ed7e39f369b24b9c157e3) is ≈ 500MB compressed (1.5GB uncompressed). Is there a smaller, Alpine-based version of the export server?

If Alpine isn't an option, I changed the [source](https://github.com/jgraph/docker-drawio/blob/master/image-export/standalone/Dockerfile) from `node` to `node:slim`, added `git`,  and was able to get it working, at only 827MB uncompressed (50% of the original size).
```
# docker images | grep export
loganmarchione/exportserver       latest              e9c4058a87b7        7 minutes ago       827MB
jgraph/export-server              latest              84212c2bb207        4 months ago        1.45GB
```

Here is the Dockerfile for that build. I was able to export a PNG, JGP, and PDF without issue.
```
FROM node:slim

LABEL maintainer="JGraph Ltd"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        git software-properties-common chromium libatk-bridge2.0-0 libgtk-3-0 && \
    apt-add-repository contrib && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        ttf-mscorefonts-installer && \
    mkdir /usr/local/drawio && \
    cd /usr/local/drawio && \
    git clone https://github.com/jgraph/draw-image-export2.git && \
    cd draw-image-export2 && \
    npm install && \
    apt-get remove -y --purge chromium

WORKDIR /usr/local/drawio/draw-image-export2

EXPOSE 8000

CMD ["npm", "start"]
```

**Comment by Floppsi1** [comment]
Hello @loganmarchione, 

may I ask you, how did you setup draw.io with the export server. I have always the problem with the PDF export that the export server tries to contact draw.io and without that connection the export does fail.
(JPG and PNG export is working even without the export server and no internet connection if I use these container jgraph/drawio:alpine.  -- at least it seems for me, perhaps I am wrong!!)

I posted my problem one day ago. The error message of the export server shows too, that it fails because it can't connect "Error: net::ERR_CONNECTION_CLOSED at 
https://www.draw.io/export3.html\n

I am using these docker-compose file https://github.com/jgraph/docker-drawio/blob/master/self-contained/docker-compose.yml.

May I ask you, if you could check what your export server is doing? Does it work without any internet connection?

Thanks a lot. F.

**Comment by loganmarchione** [comment]
@Floppsi1 - Here is the docker-compose.yml file that I use.
```
version: '3'
services:
  image-export:
    container_name: image-export
    image: jgraph/export-server
    restart: unless-stopped
    networks:
      - drawio
    expose:
      - "8000"
  drawio:
    container_name: drawio
    image: jgraph/drawio:alpine
    restart: unless-stopped
    environment:
      - EXPORT_URL=http://image-export:8000/
    networks:
      - drawio
    ports:
      - '8444:8443'
    depends_on:
      - image-export

networks:
  drawio:
```

I just unplugged my WAN connection and I also get the export3 error. I'm not sure what it's reaching out for (since it's supposed to be self-hosted)...

`warn: Handled exception: net::ERR_NAME_RESOLUTION_FAILED at https://www.draw.io/export3.html req=ip=10.10.1.71 format=png w=0 h=0 bg=#ffffff  {"stack":"Error: net::ERR_NAME_RESOLUTION_FAILED at https://www.draw.io/export3.html\n    at navigate (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/FrameManager.js:120:37)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/Page.js:674:49)\n    at Page.<anonymous> (/usr/local/drawio/draw-image-export2/node_modules/puppeteer/lib/helper.js:112:23)\n    at handleRequest (/usr/local/drawio/draw-image-export2/export.js:415:16)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}`

**Comment by Floppsi1** [comment]
@loganmarchione thanks a lot for checking. I think something did change in the last 4 month and it is not reflected in the compose file or in the docker file itself.
Hope someone of draw.io will response to my issue.

**Comment by ashrafteleb** [comment]
@loganmarchione We've updated the Docker file to use node:slim as you suggested. Thanks
@Floppsi1 We've also updated docker-compose.yml file in image-export. Set the environment variable DRAWIO_BASE_URL. Also, check self-contained/docker-compose.yml & self-contained/README.md for more details
