### ISSUE TITLE
is it possible to use GCP Iot core in real-time collaboration instead AWS Iot core?

### ISSUE THREAD

**Issue by PraveenKUMAR-M295** [jgraph/docker-drawio#70]

**Comment by davidjgraph** [comment]
We use Google App Engine, but that doesn't need a docker image. If you mean RT on GCP VMs, no.

**Comment by davidjgraph** [comment]
We've never tested it there, I doubt it would work.

**Comment by PraveenKUMAR-M295** [comment]
is there any guide to deploy draw io on Google App Engine?
