### ISSUE TITLE
README does not contain example to post a file and convert it

### ISSUE THREAD

**Issue by fatehks** [jgraph/docker-drawio#71]
The README does not contain a "curl" example that shows how to post a drawio file and convert it to png or pdf.

I have searched quite a bit for an example, but, have not found anything that works yet.

**Comment by m-mohamedin** [comment]
You can have a look at the desktop app
https://github.com/jgraph/drawio-desktop/

There are some docker images using it for dockerized export (but not maintained by JGraph)
