### ISSUE TITLE
Fix environment variable for certificate COUNTRY_CODE

### ISSUE THREAD

**Issue by unusedcow** [jgraph/docker-drawio#76]
Correction for the environment variable mapping in the `docker-entrypoint.sh` file:

In order to match the documentation and docker-compose.yml, the current line:
`COUNTRY_CODE=${COUNTRY:-'FR'}`

Should instead be:
`COUNTRY_CODE=${COUNTRY_CODE:-'FR'}`

**Comment by unusedcow** [comment]
Another related correction for environment variable mismatch on "ORGANISATION_UNIT":

- From: `ORGANISATION_UNIT=${ORGANIZATION_UNIT:-'Cloud Native Application'}`
- To: `ORGANISATION_UNIT=${ORGANISATION_UNIT:-'Cloud Native Application'}`

**Comment by m-mohamedin** [comment]
Fixed. 
Thanks for the report
