### ISSUE TITLE
EXPORT_URL and PLANT_URL environment variable are not used by docker-entrypoint.sh

### ISSUE THREAD

**Issue by level420** [jgraph/docker-drawio#78]
Using the current docker-drawio container in a nextcloud docker-compose stack, where I'm also using a export-server docker container for PDF generation.

In several docker-compose examples in this repo there are examples on how to configure the drawio container using the environment variable EXPORT_URL to point to the drawio export container within the stack.

Setting the environment Variable EXPORT_URL in the docker-compose.yml file did not have any effect.
Inspecting docker-entrypoint.sh revealed that there isn't any processing of the environment variable EXPORT_URL. The same applies to the PLANT_URL environment variable.

**Comment by m-mohamedin** [comment]
Will be added. Currently, you can use env var `DRAWIO_SELF_CONTAINED=1` which adds both EXPORT_URL and PLANT_URL

Thanks for the report
