### ISSUE TITLE
Question: how to setup github as cloud storage for self hosted drawio app

### ISSUE THREAD

**Issue by rvashishth** [jgraph/docker-drawio#87]
Is it possible to use github as cloud storage for draw.io files.

I could see https://github.com/jgraph/docker-drawio/tree/dev/self-contained mentioned gitlab, google and ms one drive but no mention of github. While we can certainly use [draw.io github app](https://github.com/apps/draw-io-app) with public github repo.

Our goal is to host draw.io locally and use it as github app. Please share if there is any manual to do so.

Thanks

**Comment by MaxDiOrio** [comment]
Just to clarify - is there no way to open/save to GitHub in the docker i mage?  I deployed the K8S image and the only option is saving/opening locally to the PC.

**Comment by cyberpuffin-digital** [comment]
Running the latest docker image I'm unable to integrate my self-hosted draw.io instance with github.  oAuth redirects back to app.diagrams.net instead of the contents of DRAWIO_BASE_URL.

**Comment by davidjgraph** [comment]
If you have a detailed report, please post one. The reports here are too vague.
