### ISSUE TITLE
GoogleDrive sign-in won't work

### ISSUE THREAD

**Issue by ghost** [jgraph/docker-drawio#98]
Preflight Checklist

    [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
    [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Describe the bug
So I've noticed a couple of bugs on the latest build.

Google Drive integration doesn't work, I click google drive, It shows the account page, I click allow and when the Oauth2 points back to my site /google per the instructions nothing is there, I can go to the same site /google and indeed nothing is running there.

To Reproduce Google Drive Issue

    Go to main screen
    Click on google drive
    Scroll down to select google account, it shows the usual app will have access to the following screen, then click allow
    Blank 500 Error page, going to /google on the same docker instance shows the same error

Expected behavior
It should continue on from there and show the save options

Screenshots
Wouldn't help, just a blank page in firefox fox and an 500 server error in chrome based browsers

draw.io version (In the Help->About menu of the draw.io editor):

    draw.io version [20.8.13]

Desktop (please complete the following information):

    OS: [Win 11]
    Browser [tested in chrome / firefox / brave / edge / multiple different pcs]
    Version [newest of all above]

Additional context
Verified Docker is running, verified port is open. I've tested with a top level domain and all /google does is returns a 500 server error after clicking Allow on the google sign in.

**Comment by ghost** [comment]
It also appears as though PDF export is broken in this version too.

**Comment by dylanvorster** [comment]
also running into this in latest version.

**Comment by dylanvorster** [comment]
think this is related: https://github.com/jgraph/docker-drawio/pull/75

**Comment by m-mohamedin** [comment]
Hi,

Can you provide more details about the server error from the logs. I just tried and it works for me.

Thanks
